class AppStrings {
  static const Map<String, Map<String, String>> _values = {
    'en': {
      'my_profile': 'My Profile',
      'account': 'ACCOUNT',
      'personal_information': 'Personal Information',
      'change_password': 'Change Password',
      'change_password_sub': 'Sends a reset link to your email',
      'notifications': 'NOTIFICATIONS',
      'email_notifications': 'Email Notifications',
      'email_notifications_sub': 'Weekly inventory reports',
      'preferences': 'PREFERENCES',
      'dark_mode': 'Dark Mode',
      'dark_mode_on': 'Navy theme (on)',
      'light_mode_on': 'Light theme (on)',
      'language': 'Language',
      'support': 'SUPPORT',
      'about_app': 'About App',
      'about_app_sub': 'Inventory Management v2.0',
      'log_out': 'Log Out',
      'log_out_confirm_title': 'Log out?',
      'log_out_confirm_body': 'You will need to sign in again to access your inventory dashboard.',
      'cancel': 'Cancel',
      'edit_profile': 'Edit Profile',
      'full_name': 'Full Name',
      'phone': 'Phone',
      'designation': 'Designation',
      'branch': 'Branch',
      'save_changes': 'Save Changes',
      'select_language': 'Select Language',
      'drones': 'Drones',
      'items': 'Items',
      'branches': 'Branches',
      'invoices': 'Invoices',
      'verified': 'Verified',
      'no_email': 'No email',
      'no_email_on_file': 'No email on file',
      'about_body': 'Chennai Drone Academy Inventory Management System.\n\nBuilt for tracking fixed assets, consumables, drone flight logs, branch stock, purchases and invoices across all facilities.\n\n© 2026 SkyLNK Unmanned Pvt. Ltd.',
      'close': 'Close',
      'about': 'About',
    },
    'ta': {
      'my_profile': 'எனது சுயவிவரம்',
      'account': 'கணக்கு',
      'personal_information': 'தனிப்பட்ட தகவல்',
      'change_password': 'கடவுச்சொல்லை மாற்று',
      'change_password_sub': 'உங்கள் மின்னஞ்சலுக்கு reset link அனுப்பப்படும்',
      'notifications': 'அறிவிப்புகள்',
      'email_notifications': 'மின்னஞ்சல் அறிவிப்புகள்',
      'email_notifications_sub': 'வாராந்திர சரக்கு அறிக்கைகள்',
      'preferences': 'விருப்பங்கள்',
      'dark_mode': 'இருள் தீம்',
      'dark_mode_on': 'நேவி தீம் (ஆன்)',
      'light_mode_on': 'லைட் தீம் (ஆன்)',
      'language': 'மொழி',
      'support': 'உதவி',
      'about_app': 'ஆப் பற்றி',
      'about_app_sub': 'இன்வென்டரி மேனேஜ்மென்ட் v2.0',
      'log_out': 'வெளியேறு',
      'log_out_confirm_title': 'வெளியேற வேண்டுமா?',
      'log_out_confirm_body': 'உங்கள் இன்வென்டரி டாஷ்போர்டை அணுக மீண்டும் உள்நுழைய வேண்டும்.',
      'cancel': 'ரத்து செய்',
      'edit_profile': 'சுயவிவரத்தை திருத்து',
      'full_name': 'முழு பெயர்',
      'phone': 'தொலைபேசி',
      'designation': 'பதவி',
      'branch': 'கிளை',
      'save_changes': 'மாற்றங்களை சேமி',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'drones': 'ட்ரோன்கள்',
      'items': 'பொருட்கள்',
      'branches': 'கிளைகள்',
      'invoices': 'இன்வாய்ஸ்கள்',
      'verified': 'சரிபார்க்கப்பட்டது',
      'no_email': 'மின்னஞ்சல் இல்லை',
      'no_email_on_file': 'மின்னஞ்சல் பதிவு இல்லை',
      'about_body': 'சென்னை ட்ரோன் அகாடமி இன்வென்டரி மேனேஜ்மென்ட் சிஸ்டம்.\n\nஎல்லா கிளைகளிலும் Fixed Assets, Consumables, drone flight logs, branch stock, purchases மற்றும் invoices கண்காணிக்க உருவாக்கப்பட்டது.\n\n© 2026 SkyLNK Unmanned Pvt. Ltd.',
      'close': 'மூடு',
      'about': 'பற்றி',
    },
    'hi': {
      'my_profile': 'मेरी प्रोफ़ाइल',
      'account': 'खाता',
      'personal_information': 'व्यक्तिगत जानकारी',
      'change_password': 'पासवर्ड बदलें',
      'change_password_sub': 'आपके ईमेल पर रीसेट लिंक भेजा जाएगा',
      'notifications': 'सूचनाएं',
      'email_notifications': 'ईमेल सूचनाएं',
      'email_notifications_sub': 'साप्ताहिक इन्वेंटरी रिपोर्ट',
      'preferences': 'प्राथमिकताएं',
      'dark_mode': 'डार्क मोड',
      'dark_mode_on': 'नेवी थीम (चालू)',
      'light_mode_on': 'लाइट थीम (चालू)',
      'language': 'भाषा',
      'support': 'सहायता',
      'about_app': 'ऐप के बारे में',
      'about_app_sub': 'इन्वेंटरी प्रबंधन v2.0',
      'log_out': 'लॉग आउट',
      'log_out_confirm_title': 'लॉग आउट करें?',
      'log_out_confirm_body': 'अपने इन्वेंटरी डैशबोर्ड तक पहुंचने के लिए आपको फिर से साइन इन करना होगा।',
      'cancel': 'रद्द करें',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'full_name': 'पूरा नाम',
      'phone': 'फ़ोन',
      'designation': 'पद',
      'branch': 'शाखा',
      'save_changes': 'परिवर्तन सहेजें',
      'select_language': 'भाषा चुनें',
      'drones': 'ड्रोन',
      'items': 'आइटम',
      'branches': 'शाखाएं',
      'invoices': 'चालान',
      'verified': 'सत्यापित',
      'no_email': 'कोई ईमेल नहीं',
      'no_email_on_file': 'कोई ईमेल दर्ज नहीं है',
      'about_body': 'चेन्नई ड्रोन अकादमी इन्वेंटरी प्रबंधन प्रणाली।\n\nसभी शाखाओं में Fixed Assets, Consumables, drone flight logs, branch stock, purchases और invoices ट्रैक करने के लिए बनाया गया।\n\n© 2026 SkyLNK Unmanned Pvt. Ltd.',
      'close': 'बंद करें',
      'about': 'के बारे में',
    },
  };

  static String tr(String code, String key) {
    return _values[code]?[key] ?? _values['en']![key] ?? key;
  }
}