// lib/services/bill_pdf_service.dart
import 'dart:convert';
import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import 'package:cda_inventory/models/bill_model.dart';

/// Generates branded PDFs for bills — either a single detailed receipt
/// (with the scanned image embedded) or a tabular summary report for a
/// filtered list of bills. Mirrors InvoicePdfService's structure so both
/// features feel consistent across the app.
class BillPdfService {
  static const PdfColor _navy = PdfColor.fromInt(0xFF0A1628);
  static const PdfColor _teal = PdfColor.fromInt(0xFF00D4AA);
  static const PdfColor _grey = PdfColor.fromInt(0xFF8FA3BF);

  /// Single bill → one-page PDF with details + the scanned receipt image.
  static Future<Uint8List> generate(BillModel bill) async {
    final doc = pw.Document();

    pw.MemoryImage? billImage;
    if (bill.imageBase64.isNotEmpty) {
      try {
        billImage = pw.MemoryImage(base64Decode(bill.imageBase64));
      } catch (_) {
        billImage = null; // Corrupt/unsupported image data — skip gracefully.
      }
    }

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              _header(),
              pw.SizedBox(height: 20),
              _detailsTable(bill),
              pw.SizedBox(height: 20),
              if (billImage != null) ...[
                pw.Text('Scanned Bill',
                    style: pw.TextStyle(
                        fontSize: 12,
                        fontWeight: pw.FontWeight.bold,
                        color: _navy)),
                pw.SizedBox(height: 8),
                pw.Container(
                  height: 380,
                  width: double.infinity,
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.grey300),
                    borderRadius: pw.BorderRadius.circular(8),
                  ),
                  child: pw.Center(
                    child: pw.Image(billImage, fit: pw.BoxFit.contain),
                  ),
                ),
              ],
              pw.SizedBox(height: 16),
              pw.Text(
                'Generated by CDA Inventory System',
                style: pw.TextStyle(fontSize: 8, color: _grey),
              ),
            ],
          );
        },
      ),
    );

    return doc.save();
  }

  /// A filtered list of bills → multi-page tabular report with a grand
  /// total, no images (keeps file size small for many bills at once).
  static Future<Uint8List> generateReport(List<BillModel> bills) async {
    final doc = pw.Document();
    final total = bills.fold<double>(0, (sum, b) => sum + b.amount);

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => context.pageNumber == 1
            ? pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 16),
          child: _header(),
        )
            : pw.SizedBox(),
        build: (context) => [
          pw.Table.fromTextArray(
            headers: ['Vendor', 'Bill No.', 'Category', 'Date', 'Amount'],
            data: bills
                .map((b) => [
              b.vendorName,
              b.billNumber,
              b.category,
              '${b.billDate.day}/${b.billDate.month}/${b.billDate.year}',
              b.amount.toStringAsFixed(2),
            ])
                .toList(),
            headerStyle: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.white,
                fontSize: 10),
            headerDecoration: const pw.BoxDecoration(color: _navy),
            cellStyle: const pw.TextStyle(fontSize: 9),
            cellAlignments: {4: pw.Alignment.centerRight},
            border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
          ),
          pw.SizedBox(height: 16),
          pw.Container(
            alignment: pw.Alignment.centerRight,
            child: pw.Text(
              'Total: Rs. ${total.toStringAsFixed(2)}  (${bills.length} bill(s))',
              style: pw.TextStyle(
                  fontSize: 12, fontWeight: pw.FontWeight.bold, color: _navy),
            ),
          ),
        ],
      ),
    );

    return doc.save();
  }

  static pw.Widget _header() {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('BILLS',
                style: pw.TextStyle(
                    fontSize: 22,
                    fontWeight: pw.FontWeight.bold,
                    color: _navy)),
            pw.SizedBox(height: 4),
            pw.Text('CDA Inventory System',
                style:
                pw.TextStyle(fontSize: 10, color: _teal, letterSpacing: 1.2)),
          ],
        ),
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
          decoration: pw.BoxDecoration(
            color: _navy,
            borderRadius: pw.BorderRadius.circular(6),
          ),
          child: pw.Text('RECEIPT',
              style: pw.TextStyle(
                  color: PdfColors.white,
                  fontSize: 10,
                  fontWeight: pw.FontWeight.bold)),
        ),
      ],
    );
  }

  static pw.Widget _detailsTable(BillModel bill) {
    final rows = <List<String>>[
      ['Vendor / Supplier', bill.vendorName],
      ['Bill Number', bill.billNumber],
      ['Amount', 'Rs. ${bill.amount.toStringAsFixed(2)}'],
      ['Category', bill.category],
      [
        'Bill Date',
        '${bill.billDate.day}/${bill.billDate.month}/${bill.billDate.year}'
      ],
      if (bill.notes.isNotEmpty) ['Notes', bill.notes],
      [
        'Uploaded On',
        '${bill.createdAt.day}/${bill.createdAt.month}/${bill.createdAt.year}'
      ],
    ];

    return pw.Table(
      columnWidths: const {
        0: pw.FlexColumnWidth(1.3),
        1: pw.FlexColumnWidth(2.5),
      },
      children: rows
          .map(
            (r) => pw.TableRow(
          children: [
            pw.Padding(
              padding: const pw.EdgeInsets.symmetric(vertical: 6),
              child:
              pw.Text(r[0], style: pw.TextStyle(fontSize: 10, color: _grey)),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.symmetric(vertical: 6),
              child: pw.Text(r[1],
                  style: pw.TextStyle(
                      fontSize: 11,
                      fontWeight: pw.FontWeight.bold,
                      color: _navy)),
            ),
          ],
        ),
      )
          .toList(),
    );
  }
}