// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHYQ2HM_FD_4Rw_sBgrbeMgJZKufYXd-Y',
    appId: '1:140087898334:android:d24233987d2cce184fd24f',
    messagingSenderId: '140087898334',
    projectId: 'cda-inventory-be82b',
    storageBucket: 'cda-inventory-be82b.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKeTY_HBxGmZx_84K-1y5TXQAdbP_CNuM',
    appId: '1:140087898334:web:487c5aa6d996442f4fd24f',
    messagingSenderId: '140087898334',
    projectId: 'cda-inventory-be82b',
    authDomain: 'cda-inventory-be82b.firebaseapp.com',
    storageBucket: 'cda-inventory-be82b.firebasestorage.app',
    measurementId: 'G-1CQDNGREBX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCohs9rkVXcO5jqLOqN8K374i2MVwl-zEE',
    appId: '1:140087898334:ios:2f707985f25e84ad4fd24f',
    messagingSenderId: '140087898334',
    projectId: 'cda-inventory-be82b',
    storageBucket: 'cda-inventory-be82b.firebasestorage.app',
    iosBundleId: 'com.example.cdaInventory',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCohs9rkVXcO5jqLOqN8K374i2MVwl-zEE',
    appId: '1:140087898334:ios:2f707985f25e84ad4fd24f',
    messagingSenderId: '140087898334',
    projectId: 'cda-inventory-be82b',
    storageBucket: 'cda-inventory-be82b.firebasestorage.app',
    iosBundleId: 'com.example.cdaInventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKeTY_HBxGmZx_84K-1y5TXQAdbP_CNuM',
    appId: '1:140087898334:web:3a9b330ebe09d3ea4fd24f',
    messagingSenderId: '140087898334',
    projectId: 'cda-inventory-be82b',
    authDomain: 'cda-inventory-be82b.firebaseapp.com',
    storageBucket: 'cda-inventory-be82b.firebasestorage.app',
    measurementId: 'G-02BH657BY0',
  );
}
